# Use a imagem oficial do Node.js com uma versão compatível com Next.js
FROM node:18-alpine

# Define o diretório de trabalho no container
WORKDIR /app

# Copia os arquivos de dependências para o diretório de trabalho
COPY package.json package-lock.json ./

# Instala as dependências
RUN npm install

# Copia o restante do código da aplicação para o diretório de trabalho
COPY . .

# Faz o build da aplicação Next.js
RUN npm run build

# Expõe a porta que o Next.js utiliza (3000 por padrão)
EXPOSE 3000

# Define o comando para iniciar o servidor de produção do Next.js
CMD ["npm", "start"]
