# Use uma imagem oficial do Python 3.11 slim como base
FROM python:3.11-slim

# Define o diretório de trabalho no container
WORKDIR /usr/src/app

# Copia o arquivo de dependências para o container
COPY requirements.txt ./

# Instala as dependências listadas no requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copia o restante do código da aplicação para o container
COPY . .

# Expõe a porta 5000 para comunicação externa
EXPOSE 5000

# Comando para rodar a aplicação
CMD ["python", "main.py"]